# This is NOT meant to be used in projects! It only tests the starzel-buildout.
language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout

  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg

  - echo "[variables]" > $HOME/mrbob_answers.txt
  - echo "package.type = Basic" >> $HOME/mrbob_answers.txt
  - echo "package.namespace = project" >> $HOME/mrbob_answers.txt
  - echo "package.namespace2 =" >> $HOME/mrbob_answers.txt
  - echo "package.name = site" >> $HOME/mrbob_answers.txt
  - echo "package.description = A Dummy package" >> $HOME/mrbob_answers.txt
  - echo "author.name = Philip Bauer" >> $HOME/mrbob_answers.txt
  - echo "author.email = bauer@starzel.de" >> $HOME/mrbob_answers.txt
  - echo "author.github.user = pbauer" >> $HOME/mrbob_answers.txt
  - echo "author.irc = irc.freenode.org#plone" >> $HOME/mrbob_answers.txt
  - echo "plone.version = 4.3.11" >> $HOME/mrbob_answers.txt

install:
  - ln -s local_develop.cfg local.cfg
  - echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
  - pip install -r requirements.txt
  - pip install mr.bob
  - pip install bobtemplates.plone

script:
  - buildout -N
# create a package 'project.site' using bobtemplates.plone using mrbob_answers.txt
  - mkdir src
  - mrbob -O src/project.site --config $HOME/mrbob_answers.txt bobtemplates:plone_addon
# add that package to buildout.cfg in eggs, testeggs, auto-checkout and [sources]
  - sed -i "15i \    project.site" buildout.cfg
  - sed -i "19i \    project.site [test]" buildout.cfg
  - sed -i "23i \    project.site" buildout.cfg
  - sed -i "29i project.site = fs project.site full-path=\${buildout\:directory}/src/project.site" buildout.cfg
# pinn versions of dependencies of the new package
  - echo "[versions]" >> buildout.cfg
  - echo "collective.elephantvocabulary = 0.2.5" >> buildout.cfg
  - echo "icalendar = 3.11.2" >> buildout.cfg
  - echo "plone.api = 1.5.1" >> buildout.cfg
  - echo "plone.event = 1.3.3" >> buildout.cfg
  - echo "plone.formwidget.querystring = 1.1.8" >> buildout.cfg
  - echo "Products.DateRecurringIndex = 2.1" >> buildout.cfg
# re-run buildout
  - buildout -N
# run tests with the new package using coverage
  - bin/coverage-test
